import { z } from "zod";

export const listingSchema = z.object({
  id: z.number().int(),
  categoryId: z.number().int().nullable(),
  listingCode: z.string(),
  title: z.string(),
  brand: z.string(),
  model: z.string(),
  variant: z.string().nullable(),
  modelYear: z.number().int().nullable(),
  registrationYear: z.number().int().nullable(),
  vehicleType: z.string().nullable(),
  bodyStyle: z.string().nullable(),
  exteriorColor: z.string().nullable(),
  interiorColor: z.string().nullable(),
  listingPriceInr: z.number().int(),
  negotiable: z.boolean(),
  estimatedMarketValueInr: z.number().int().nullable(),
  ownershipType: z.string().nullable(),
  sellerType: z.string().nullable(),
  registrationState: z.string().nullable(),
  registrationCity: z.string().nullable(),
  totalKmDriven: z.number().int().nullable(),
  mileageKmpl: z.number().nullable(),
  engineType: z.string().nullable(),
  engineCapacityCc: z.number().int().nullable(),
  powerBhp: z.number().int().nullable(),
  transmissionType: z.string().nullable(),
  fuelType: z.string().nullable(),
  batteryCapacityKwh: z.number().nullable(),
  overallConditionRating: z.number().nullable(),
  serviceHistoryAvailable: z.boolean().nullable(),
  airbagsCount: z.number().int().nullable(),
  infotainmentScreenSize: z.string().nullable(),
  locationCity: z.string().nullable(),
  locationState: z.string().nullable(),
  dealerRating: z.number().nullable(),
  inspectionStatus: z.string().nullable(),
  inspectionScore: z.number().nullable(),
  listingStatus: z.string(),
  featuredListing: z.boolean(),
  isSplus: z.boolean(),
  isNewCar: z.boolean(),
  newCarType: z.string().nullable(),
  viewsCount: z.number().int().nullable(),
  favoritesCount: z.number().int().nullable(),
  leadCount: z.number().int().nullable(),
  promotionTier: z.string().nullable(),
  images: z.array(z.string()),
  interiorImages: z.array(z.string()),
  exteriorImages: z.array(z.string()),
  engineImages: z.array(z.string()),
  tireImages: z.array(z.string()),
  damageImages: z.array(z.string()),
  additionalNotes: z.string().nullable(),
  specs: z.record(z.unknown()),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export type Listing = z.infer<typeof listingSchema>;

export const createListingSchema = z.object({
  listingCode: z.string().min(1).max(50),
  title: z.string().min(1).max(300),
  brand: z.string().min(1).max(100),
  model: z.string().min(1).max(100),
  categoryId: z.number().int().positive().nullable().optional(),
  variant: z.string().max(200).nullable().optional(),
  modelYear: z.number().int().min(1900).max(2100).nullable().optional(),
  registrationYear: z.number().int().min(1900).max(2100).nullable().optional(),
  vehicleType: z.string().max(50).nullable().optional(),
  bodyStyle: z.string().max(50).nullable().optional(),
  exteriorColor: z.string().max(50).nullable().optional(),
  interiorColor: z.string().max(50).nullable().optional(),
  listingPriceInr: z.number().int().min(0).optional(),
  negotiable: z.boolean().optional(),
  estimatedMarketValueInr: z.number().int().min(0).nullable().optional(),
  ownershipType: z
    .enum(["First", "Second", "Third", "Fourth+"])
    .nullable().optional(),
  sellerType: z
    .enum(["Dealer", "Individual", "Certified Dealer"])
    .nullable().optional(),
  registrationState: z.string().max(100).nullable().optional(),
  registrationCity: z.string().max(100).nullable().optional(),
  totalKmDriven: z.number().int().min(0).nullable().optional(),
  mileageKmpl: z.number().min(0).nullable().optional(),
  engineType: z.string().max(100).nullable().optional(),
  engineCapacityCc: z.number().int().min(0).nullable().optional(),
  powerBhp: z.number().int().min(0).nullable().optional(),
  transmissionType: z
    .enum(["Manual", "Automatic", "CVT", "DCT", "AMT"])
    .nullable().optional(),
  fuelType: z
    .enum(["Petrol", "Diesel", "Electric", "Hybrid", "CNG", "LPG"])
    .nullable().optional(),
  batteryCapacityKwh: z.number().min(0).nullable().optional(),
  overallConditionRating: z.number().min(0).max(10).nullable().optional(),
  serviceHistoryAvailable: z.boolean().nullable().optional(),
  airbagsCount: z.number().int().min(0).nullable().optional(),
  infotainmentScreenSize: z.string().max(20).nullable().optional(),
  locationCity: z.string().max(100).nullable().optional(),
  locationState: z.string().max(100).nullable().optional(),
  dealerRating: z.number().min(0).max(5).nullable().optional(),
  inspectionStatus: z.string().max(30).nullable().optional(),
  inspectionScore: z.number().min(0).max(100).nullable().optional(),
  listingStatus: z.string().max(20).optional(),
  featuredListing: z.boolean().optional(),
  isSplus: z.boolean().optional(),
  isNewCar: z.boolean().optional(),
  newCarType: z.string().max(30).optional(),
  promotionTier: z.string().max(20).optional(),
  images: z.array(z.string()).optional(),
  interiorImages: z.array(z.string()).optional(),
  exteriorImages: z.array(z.string()).optional(),
  engineImages: z.array(z.string()).optional(),
  tireImages: z.array(z.string()).optional(),
  damageImages: z.array(z.string()).optional(),
  additionalNotes: z.string().optional(),
  specs: z.record(z.unknown()).optional(),
});

export type CreateListingInput = z.infer<typeof createListingSchema>;

export const updateListingSchema = createListingSchema.partial();

export type UpdateListingInput = z.infer<typeof updateListingSchema>;

export const listingFilterSchema = z.object({
  search: z.string().optional(),
  brand: z.string().optional(),
  model: z.string().optional(),
  fuelType: z.string().optional(),
  transmissionType: z.string().optional(),
  bodyStyle: z.string().optional(),
  ownershipType: z.string().optional(),
  sellerType: z.string().optional(),
  locationCity: z.string().optional(),
  exteriorColor: z.string().optional(),
  listingStatus: z.string().optional(),
  featuredListing: z.coerce.boolean().optional(),
  isSplus: z.coerce.boolean().optional(),
  isNewCar: z.coerce.boolean().optional(),
  priceMin: z.coerce.number().int().min(0).optional(),
  priceMax: z.coerce.number().int().min(0).optional(),
  yearMin: z.coerce.number().int().optional(),
  yearMax: z.coerce.number().int().optional(),
  kmMax: z.coerce.number().int().min(0).optional(),
  categoryId: z.coerce.number().int().positive().optional(),
  sortBy: z
    .enum(["price_asc", "price_desc", "year_desc", "km_asc", "newest"])
    .optional(),
  page: z.coerce.number().int().positive().optional(),
  limit: z.coerce.number().int().positive().max(100).optional(),
});

export type ListingFilter = z.infer<typeof listingFilterSchema>;
